# Generated by Django 5.0.3 on 2024-04-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Checked Out", "Checked Out"),
                            ("Reserved", "Reserved"),
                            ("On hold", "On hold"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_by", models.CharField(max_length=200)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
